---
- name: Create a directory if it does not exist
  file:
    path: "{{ project_path }}"
    state: directory
    mode: '0755'
  tags:
    - copy_image

- name: Copy image to remote
  copy:
    src: "{{ abs_img_path }}"
    dest: "{{ project_path }}/{{ image }}.tar"
    mode: '0744'
    remote_src: true
  tags:
    - copy_image

- name: Load docker image to minikube docker
  shell:
    cmd: "eval $(minikube docker-env) && docker load -i {{ project_path }}/{{ image }}.tar"
  tags:
    - copy_image
